config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "events#index"
  resources :events, only: [:new, :create, :show]
  resources :users, only: [:show]
  resources :registrations, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: "User", foreign_key: "user_id"

    has_many :registrations

    has_many :attendees, through: :registrations, source: 'user'

    scope :past, -> { where('event_date < ?', Date.today) }
    scope :future, -> { where('event_date > ?', Date.today) }  
end

app/models/registration.rb
class Registration < ApplicationRecord
    belongs_to :event, optional: true
    belongs_to :user, optional: true

    validates :user_id, uniqueness: {scope: :event_id, message: "User already registered for this event!"}, presence: true
    validates :event_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable

  validates :username, uniqueness: true, presence: true
  validates :password, presence: true

  has_many :events, class_name: 'Event', foreign_key: 'user_id'

  has_many :registrations

  has_many :attended_events, through: :registrations, source: 'event'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :require_login, only: [:new, :create]

  def index
    @events = Event.all
    @users = User.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @event = Event.find(params[:id])
    @attendees = @event.attendees
  end

  private

  def require_login
    unless user_signed_in?
      flash[:error] = 'You must be logged in to do that.'
      redirect_to root_path
    end
  end

  def event_params
    params.require(:event).permit(:event_date, :event_name)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

    before_action :require_login
    
    def create

        @event_id = params[:event_id] 

        @registration = Registration.new(user_id: current_user[:id], event_id: @event_id)

        if @registration.save
            flash[:notice] = 'Successfully Registered!'
            redirect_to root_path
        else
            @registration.errors.any? ? flash[:error] = @registration.errors.full_messages[0].slice(5..) : flash[:error] = 'Registration Error.'
            redirect_to events_path
        end
    end

    private

    def require_login
        unless user_signed_in?
          flash[:error] = 'You must be logged in to do that.'
          redirect_to events_path
        end
    end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
        @events = User.find(params[:id]).events
        @attended_events = User.find(params[:id]).attended_events
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/events/index.html.erb
<%= flash[:error] ? flash[:error] : nil %>

<h1>Index</h1>
<% if !user_signed_in? %>
    <%= link_to 'Sign In', new_user_session_path %>
<% else %>
    <p>Logged in as: <%= current_user[:username] %></p>
    <%= link_to 'Log Out', destroy_user_session_path, data: {turbo_method: :delete} %>
<% end %>
<br>
<%= link_to 'Create New Event', new_event_path %>
<div id='content'>
    <div id='users'>
        <h2>Users:</h2>
        <% if @users.empty? %>
            <p>No users.</p>
        <% else %>
            <ul>
                <% @users.each do |user| %>
                    <li><%= link_to user[:username], user_path(user) %></li>
                <% end %>
            </ul>
        <% end %>
    </div>
    <div id='events'>
        <h2>Events:</h2>
        <% if @events.empty? %>
            <p>No events.</p>
        <% else %>
            <ul>
                <% @events.each do |event| %>
                    <li><%= link_to event[:event_name], event_path(event) %></li>
                <% end %>
            </ul>
        <% end %>
    </div>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= form_with model: @event do |f| %>
    <%= f.label :event_date, 'Event Date: ' %>
    <%= f.date_select :event_date %>
    <br>
    <%= f.label :event_name, 'Event Name: ' %>
    <%= f.text_field :event_name, placeholder: 'enter event name' %>
    <%= f.submit 'Submit' %>
<% end %>

app/views/events/show.html.erb
<%= flash[:error] ? flash[:error] : nil %>
<%= flash[:notice] ? flash[:notice] : nil %>
<h1><%= @event.event_name %></h1>

<p>Event Date: <%= @event.event_date %></p>
<p>Organized by: <%= @event.creator.username %></p>

<h2>Attending Guests:</h2>
<% if @attendees.empty? %>
        <p>No attendees.</p>
 <% else %>
    <% @attendees.each do |attendee| %>
        <p><%= attendee[:username] %></p>
    <% end %>
<% end %>

<%= button_to 'I will attend!', registrations_path(event_id: @event[:id]) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class='notice'><%= notice %></p>
    <p class='alert'><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1>User: <%= @user[:username] %></h1>

<h2>Created Events:</h2>
<% if @events.empty? %>
        <p>No events.</p>
<% else %>
    <% @events.each do |event| %>
        <p><%= event[:event_name] %></p>
    <% end %>
<% end %>

<h2>Registered Events:</h2>

<div class='user_events'>
    <div class='event_div'>
        <h3>Past Events</h3>
        <% if @attended_events.past.empty? %>
            <p>No events.</p>
        <% else %>
            <% @attended_events.past.each do |event| %>
                 <p><%= event[:event_name] %></p>
            <% end %>
        <% end %>
    </div>
    <div class='event_div'>
        <h3>Upcoming Events</h3>
        <% if @attended_events.future.empty? %>
            <p>No events.</p>
        <% else %>
            <% @attended_events.future.each do |event| %>
                 <p><%= event[:event_name] %></p>
            <% end %>
        <% end %>
    </div>
</div>